### PR TITLE
Fixes #14.

### LINKED ISSUE #14: Requests with a bad resource should expect 404s not 400s
**Version**
[Master branch](https://github.com/adlnet/xAPI_LRS_Test/tree/master ) at commit ff9cde184f7ad06db35d4e011e41994499b65720

**Steps to reproduce**
Run `grunt --feature="features/about.feature" --grep="Bad about: typical request with bad resource 'abouts'"`.

**Expected behaviour**
Test passes when request receives a *404* response. I expect this because the [specification](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#details-30) states:
> 404 Not Found - Indicates the requested resource was not found.

**Actual behaviour**
Test passes when request receives a *400* response. A bad *resource* is not usually considered to be an invalid or missing *argument*, hence, this is unexpected behaviour because the [specification](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#details-30) states:
> 400 Bad Request - Indicates an error condition caused by an invalid or missing argument. The term "invalid arguments" includes malformed JSON or invalid Object structures.

**LRS**
[Learning Locker](https://github.com/LearningLocker) on the [issue/conformance branch](https://github.com/LearningLocker/learninglocker/tree/issue/conformance) at commit [6828bec](https://github.com/LearningLocker/learninglocker/commit/6828bec51b6d2702a4be711ffe0957e274400b0e)

### PR DESCRIPTION
**Pull request by ryansmith94**
This fixes #14 according to the [xAPI error codes](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#71-error-codes).

### CODE REVIEW

**Comment by garemoko** [comment]
Looking at the code, the change looks good to me. It'd be worth having somebody other than the PR author run the tests to confirm, but other than that, +1 from me.

**Comment by ryansmith94** [comment]
:+1:

**Comment by fugu13** [comment]
Right now there's nothing preventing an LRS from hosting additional resources, of course, so *not* 404ing there would not be a spec violation. I don't see any benefit from having the tests for negative resources at all.

**Comment by ryansmith94** [comment]
I agree, do we all agree that the negative resource tests should be removed? @fugu13 @garemoko @brianjmiller

**Comment by garemoko** [comment]
The error codes and consistency of error codes is very helpful for activity providers both during development to debug, but also within the application so that it can respond correctly. It's helpful to know that a certain error code means I may have mistyped the resource endpoint. In most cases libraries cover this for me, but none of the libraries have complete spec coverage (AFAIK) and we don't cover all programming languages. 

My point is that it's helpful to check that the LRS is returning the right code in the right situation.

Now, I do appreciate that an LRS could in theory use any resources it likes, but in practice I would like to test at least one invalid endpoint to check the error code. Something like "/not-a-valid-resource" should be fine for all practical purposes.

**Comment by ryansmith94** [comment]
I agree with that Andrew.

**Comment by ryansmith94** [comment]
Alternatively you could try to get a document from one of the document APIs that hasn't been created. I believe that should return a 404 too.

**Comment by fugu13** [comment]
I'm fine with a really implausible resource being checked for 404.

There should also be tests for document API keys that don't exist, but that's separate.

**Comment by garemoko** [comment]
"that's separate" +1

**Pull request closed without merging**
