### PR TITLE
Changes response from 401 to 400.

### PR DESCRIPTION
**Pull request by ryansmith94**
https://github.com/adlnet/xAPI_LRS_Test/pull/38

### CODE REVIEW

**Comment by ryansmith94** [comment]
Bump. Trying to clear my issues list on Github.

**Comment by ryansmith94** [comment]
Probably going to close this because of inactivity @garemoko @brianjmiller

**Comment by garemoko** [comment]
@andyjohnson can we discuss these at least briefly on this week's call? We need to come up with a plan to get things moving here.

**Comment by ryansmith94** [comment]
Closing because of inactivity

**Pull request closed without merging**
