### PR TITLE
Fixes #16 #23

### PR DESCRIPTION
**Pull request by ryansmith94**
This fixes #16 #23 according to the [xAPI error codes](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#71-error-codes).

### CODE REVIEW

**Comment by garemoko** [comment]
Looks right to me. +1 pending testing the tests. 

CC: https://github.com/adlnet/xAPI-Spec/issues/600

**Comment by ryansmith94** [comment]
Thanks Andrew :+1:

**Comment by garemoko** [comment]
Re-reading adlnet/xAPI-Spec#600 @fugu13's position is that in fact either 400 or 401 or even 500 are ok for this particular case. I suggest we hold off merging this until the spec issue has a consensus and that we plan to discuss this on a call sometime soon (cc: @andyjohnson).

**Comment by ryansmith94** [comment]
If possible please try to get this issue resolved to a point where we all through the same error code for the sake of testing.

**Comment by garemoko** [comment]
Sorry @ryansmith94 - conclusion on the call was that either 400 or 401 are ok. Not sure how you represent that in the test suite code.

**Comment by ryansmith94** [comment]
Damn, it seems to me that the only options are to accept multiple response codes somehow (not sure if that's possible @brianjmiller) or remove the test.

**Comment by brianjmiller** [comment]
@ryansmith94 the step commonly used to verify the returned status code can take a list, multiple formats accepted including one that is or'd. See https://github.com/adlnet/xAPI_LRS_Test/blob/master/src/steps/base.js#L278

**Comment by ryansmith94** [comment]
@brianjmiller nice that's awesome, I need to learn how to do that :+1: I'll try to change this PR if I think about it :+1:

**Pull request closed without merging**
